# Site settings
title: Spencer Melnick
header-img: img/electrical_component_bg.jpg
email: smelnick97@gmail.com
description: "My personal blog"
baseurl: ""
url: "http:/spencermelnick.me"
github_username:  spencer-melnick

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
